<?php
/**
 * @file
 * Description here.
 */

/**
 * hook_menu
 */
function xs_menu() {
  $items = array();
  $items['admin/config/xs'] = array(
    'title' => 'xs config',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('xs_config_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'xs.admin.inc',
  );

  // return $items;
}
/* */
function xs_form_alter(&$form, &$form_state) {
  // TODO: find a clever way of listing forms where to use / not use it
  $form['xsxtrainfo'] = array(
    '#type' => 'textfield',
    '#title' => 'Important info',
    '#attributes' => array('class' => array('xsxtra')),
    //'hidden' => true,
  );
  // TODO: should we do this in validation instead ?
  array_unshift($form['#submit'], 'xs_submit');
  
  ctools_add_css('xs','xs');
}
// */

function xs_submit(&$form, &$form_state) {
  // check if they provided any info, if yes, ask them if they're human or what
}
